### ISSUE TITLE
Unable to configure nodeSelector and tolerations for apprepo-kubeapps-sync-* pod(s)

### ISSUE THREAD

**Issue by tmeltser** [vmware-tanzu/kubeapps#4574]
I'm trying to run kubeapps on Rancher RKE1 **mixed cluster** (both Linux and Windows nodes).
This kind of cluster maintains a special taint on the Linux nodes (cattle.io/os=linux:NoSchedule), which if not set prevents Linux pods from running on these nodes.
I've went through the complete values.yaml file and customized all feasible places (frontend, dashboard, **apprepository**, kubeops, kubeappsapis, assetsvc) for the applicable **nodeSelector and tolerations**.
The only thing left missing are the apprepo-kubeapps-sync-* pods (controlled by apprepo-kubeapps-sync-bitnami cronjob which is controlled by bitnami AppRepository).

Can anyone advise how can I customize this missing part (**nodeSelector and tolerations**) via helm customization?

**Comment by absoludity** [comment]
Hi @tmeltser . Yes, the pods for the sync-jobs are added (a CronJob) when you add the AppRepository (or, if you mean you're using the default Bitnami repository, they'll be created via that during install when the AppRepository is added).

You can add a custom pod spec template when adding an app repository (or edit the Bitnami one, if using the default) to control things like labels and node selectors etc. See https://github.com/vmware-tanzu/kubeapps/blob/main/docs/howto/private-app-repository.md#modifying-the-synchronization-job for more info (contrary to the name of the doc file, it's not just for private app repos).

**Comment by tmeltser** [comment]
Hi @absoludity,
Thank you for the prompt reply.

I'm not looking to add a custom repository, all I want to do is allowing the default one (Bitnami) to operate normally by specifying node selector and tolerations to the AppRepository pod(s) - and I don't see applicable place for it in the **values.yaml**.

Actually, the reason for my query is that I'm assuming the error I have is related to this missing setup, **but maybe it isn't related to it?**

This is the error:
```
Unable to list apps
Invalid GetInstalledPackageSummaries response from the plugin helm.packages:
Code: Internal
Description: Error while fetching related charts: pq: relation "charts" does not exist
```

**Comment by absoludity** [comment]
Yes, that error means that a sync-job hasn't yet run successfully (as the pg tables are created when the sync-job runs). So I think you're correct is guessing that it's the cause. You may be able to verify that by checking for the sync job pods and checking the log there.

The [value you're looking for in the values.yaml is the `initialRepos`](https://github.com/vmware-tanzu/kubeapps/blob/main/chart/kubeapps/values.yaml#L851-L887). It defaults to the plain bitnami repo, but you should be able to set that value to the bitnami repo (url) with a nodeSelector etc. as needed. (see[ apprepositories.yaml](https://github.com/vmware-tanzu/kubeapps/blob/main/chart/kubeapps/templates/apprepository/apprepositories.yaml#L41-L43) if you're keen to see where in the template that is translated into the actual syncJobPodTemplate of the app repository).

**Comment by tmeltser** [comment]
Hi @absoludity,
I've made the proposed change (although I used ) `--set apprepository.initialRepos=[]` instead of  `--set apprepository.initialRepos={}`, now I don't see any faulted pods (although being able to configure tolerations would have been a better solution of course), but I still get the same error:
```
Unable to list apps
Invalid GetInstalledPackageSummaries response from the plugin helm.packages:
Code: Internal
Description: Error while fetching related charts: pq: relation "charts" does not exist
```
Any thoughts on what may the issue here (or at least on which logs to look at)?

**Comment by absoludity** [comment]
> **didn't define any repositories, hope this isn't a problem...**

Yes, that will mean that there is no sync job run at all yet (and so no postgres tables/relations). The idea here is to install Kubeapps without using the chart helpers for the initial repository, and instead *add* your own repository without the restrictions of the chart config, with `kubectl apply -f my-custom-bitnami-repository.yaml` so that you can set the syncPodTemplate to whatever you want.

If you want to see what `my-custom-bitnami-repository.yaml` should look like, you can just repeat your old install first where you set the nodeSelector, then output the resulting apprepository to a yaml file.

Hope that helps.

**Comment by tmeltser** [comment]
Well, after the last hint it is working now with the manual appRepository in place - 10x.

_Would have been much accommodating if we could also add the tolerations to the helm customization, just like the nodeSelector._

@absoludity - your assistance is much appreciated.

**Comment by absoludity** [comment]
Excellent, glad you got it working. And yes, totally agree, let's now leave this issue open for updating the chart to accommodate seeing the taints with the nodeSelector. That was the much more obvious approach.

**Comment by absoludity** [comment]
Fixed upstream in https://github.com/bitnami/charts/pull/10511 . I used your tolerations example in the values.yaml example :)

**Comment by tmeltser** [comment]
I just tested the updated helm chart and it doesn't work (at least for me) - **now I didn't use any custom repositories**, but wanted to utilize what the chart brings, with adding the proper tolerations (and node selector), but I get the same error as before.
I'm using the following clause within my customization file:
```
apprepository:
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
  - key: "cattle.io/os"
    operator: "Equal"
    value: "linux"
    effect: "NoSchedule"
```
I still see, as before, that the tolerations (_**and the node selector**_) didn't "stick" to the sync job/pods for Bitnami.

Please advise.

**Comment by absoludity** [comment]
Hi @tmeltser . What you have specified above are the tolerations and node selector for the app repository controller deployment only, not for a specific repository - even if it's the one that the chart brings. To do what you want to do (set the node selector and tolerations for the default bitnami char), you need to use the values as follows:

```
apprepository:
  initialRepos:
    - name: bitnami
      url: https://charts.bitnami.com/bitnami
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "cattle.io/os"
        operator: "Equal"
        value: "linux"
        effect: "NoSchedule"
```

With that, I see sync jobs with the expected node selector and tolerations:
```
...
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext:
    runAsUser: 1001
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: cattle.io/os
    operator: Equal
    value: linux
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300

```

**Comment by tmeltser** [comment]
Hi @absoludity,
This is what I did before the correction and it indeed worked.
I was under the impression (**or maybe hope**) that the correction would enable the "injection" of the tolerations (and node selectors) into the default apprepository, without the need to do it implicitly...

**Comment by absoludity** [comment]
> Hi @absoludity, This is what I did before the correction and it indeed worked.

The work-around that we did before the correction was to let the app repository be created then explicitly set the `syncJobPodTemplate` with the required tolerations etc. I think? All my change upstream to the chart did was enable us to specify the tolerations (for an app repository) as part of the initialRepos... so you can specify it at deployment time and not need to explicitly update the `syncJobPodTemplate` at all.

> I was under the impression (**or maybe hope**) that the correction would enable the "injection" of the tolerations (and node selectors) into the default apprepository, without the need to do it implicitly...

It enables you to specify the tolerations for any initial repository. If you mean that you were hoping you could specify just the tolerations and not re-specify the default bitnami repo... you can, but it's a bit of a pain, because the `initialRepos` is a *list* of repositories. There is some incantation you can use with your helm command (`--set apprepository.initialrepos[0].tolerations .... etc`), but I find it easier to just set the initial repos list including the url in a values.yaml.

hope that helps!

**Comment by absoludity** [comment]
Yeah, unfortunately the `tolerations` and `nodeSelector` under the apprepository fulfill a different purpose. We have those on all services (`apprepository`, `frontend`, `dashboard`, etc.) so that people can ensure the actual *service* (not the sync job for an app repository), run on specific pods.
